databases:
  - name: mysite
    databaseName: mysite_development
    user: mysite_development_user

services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false